// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhpj9-Jz0Ego_NXSewaTtW7aVyWI5YtgU',
    appId: '1:1061076532865:web:8ffa8e4bc4d56007725780',
    messagingSenderId: '1061076532865',
    projectId: 'authtutorial-7be44',
    authDomain: 'authtutorial-7be44.firebaseapp.com',
    storageBucket: 'authtutorial-7be44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMSdqLOTLjDjdvHJ8ME4HUma_AfHdGsAo',
    appId: '1:1061076532865:android:e8dcccefd3da5a93725780',
    messagingSenderId: '1061076532865',
    projectId: 'authtutorial-7be44',
    storageBucket: 'authtutorial-7be44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw7g4j_hdyzNKaDmfj4egZfospDE8qdjM',
    appId: '1:1061076532865:ios:a416eef4700dca6e725780',
    messagingSenderId: '1061076532865',
    projectId: 'authtutorial-7be44',
    storageBucket: 'authtutorial-7be44.appspot.com',
    iosBundleId: 'com.example.authenticationApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw7g4j_hdyzNKaDmfj4egZfospDE8qdjM',
    appId: '1:1061076532865:ios:0acebc24c6e48f23725780',
    messagingSenderId: '1061076532865',
    projectId: 'authtutorial-7be44',
    storageBucket: 'authtutorial-7be44.appspot.com',
    iosBundleId: 'com.example.authenticationApplication.RunnerTests',
  );
}
